### ISSUE TITLE
log as different event types even they have the same fields

### ISSUE THREAD

**Issue by sixinli** [palantir/dropwizard-web-logger#11]
let me know if i should PR this, not sure if the current setting is intentional 

currently if i have this, it will be logged as resourceLoadTime for all:
```yml
- type: fullPageLoadTime
  fields: [details, source, type, user, utcTimestamp]
- type: resourceLoadTime
  fields: [details, source, type, user, utcTimestamp]
```
we could have a logEventContent() function overload that takes an event type
